### ISSUE TITLE
Madden franchise editor doesn't open player sheet (21)

### ISSUE THREAD

**Issue by bnthomason** [bep713/madden-franchise-editor#25]
Hey. I have a problem with opening the player sheet. I retrieved the contents from the exe but when opening the player sheet, the editor will hang for a bit, access it, then go "blank".

Video of the problem, showing it working with M20, but not M21

https://www.youtube.com/watch?v=yEH6a2UfAVg

**Comment by NoahJele** [comment]
The reason why is because the pinned tables were based on M21's first release, but those table numbers changed with subsequent updates. Delete those pinned tables, and instead search 'Player' in the table editor, which will take you to the actual player table. Then you can pin that table for easy access.

**Comment by matthewpanetta** [comment]
Closing as @NoahJele is correct. The pins were made at the very beginning of M21 and the tables have since changed. It'd be complicated to update these dynamically, as some tables have duplicate names.

This is good to know, though, because the same will happen for M22. Thanks for bringing this up :)

**Comment by bnthomason** [comment]
Ok, I deleted all the pins, now what? When I search player, it takes me to 359 player, and shows "Player 0, Player 1, and player 2"

Maybe I did it wrong
![Uploading Player Tab.png…]()

**Comment by matthewpanetta** [comment]
@bnthomason I can't see your pic but that is most likely a Player[] table ([] meaning array). You want the actual Player table, which for my M21 is table 130 - (4226) Player. Yours should be around the same number. It'll have many rows and columns in it.
