### ISSUE TITLE
October title update = broken ability editor

### ISSUE THREAD

**Issue by ElectronicMonolith** [bep713/madden-franchise-editor#3]
So I just tried to edit some abilities on a file post-update and noticing the ability editor will just endlessly load. I'm playing a offline franchise and have some older saves that haven't been "converted" by the game yet and the editor loads them fine. 

Just me or no?

**Comment by hotepzero** [comment]
Signed up just to say I'm having the same exact issues, ability editor doesn't load. Would love to get this fixed to go with the new patch

**Comment by jstubbs73** [comment]
> So I just tried to edit some abilities on a file post-update and noticing the ability editor will just endlessly load. I'm playing a offline franchise and have some older saves that haven't been "converted" by the game yet and the editor loads them fine.
> 
> Just me or no?

No not just you, I am having the same issue.  I'll add that the schedule editor of the same file and what seems to be files saves after the patch have no team icons or actual info only characters.

**Comment by Ar4bAce** [comment]
Have this issue too

**Comment by EduardoPena75** [comment]
This is a recent issue. Apparently in one of the Madden 20 updates they added the new "Fear" ability. Since it is brand new it wasn't part of bep's ability editor and I think that's what is causing this new problem. 

Now when you go in to change abilities you get a screen with a loading symbol on it that never goes away.

**Comment by matthewpanetta** [comment]
Hey guys,

I'm working on an update now and hope to have it out soon. The new update made changes to the franchise schema (you can see this file in frosty under Legacy Explorer -> common -> Franchise -> FranTkData -> 0 -> Franchise-Schemas) its just an XML file that defines each table's attributes and enum values. There were a few tables that have added attributes so some of them aren't parsed correctly, resulting in crazy or null values.

The new version will have the newest schema, a kinda-smart schema picker based on the franchise file, and a way that you can override the schema with a custom file from Frosty in case this happens and I'm not around to push out an update. If something breaks in the future due to an update, the schema is the most likely problem.

**Comment by bep713** [comment]
^ That's me, i was using my main account lol oops :D

**Comment by hotepzero** [comment]
> Hey guys,
> 
> I'm working on an update now and hope to have it out soon. The new update made changes to the franchise schema (you can see this file in frosty under Legacy Explorer -> common -> Franchise -> FranTkData -> 0 -> Franchise-Schemas) its just an XML file that defines each table's attributes and enum values. There were a few tables that have added attributes so some of them aren't parsed correctly, resulting in crazy or null values.
> 
> The new version will have the newest schema, a kinda-smart schema picker based on the franchise file, and a way that you can override the schema with a custom file from Frosty in case this happens and I'm not around to push out an update. If something breaks in the future due to an update, the schema is the most likely problem.

YES! Thank you for the update! I have not played Madden since the ability editor broke, and was researching hard into how to rid the patch (which you can't). I am stoked for this update, hoping it's soon, and can't wait to start playing again! Thanks for all your hard work! Would be happy to donate to you as well.

**Comment by bep713** [comment]
Alright, new version posted. Let me know if you find any issues. I haven't had a lot of time to test and wanted to get something out there. I should have some time to tomorrow if anything comes up.

**Comment by hotepzero** [comment]
> Alright, new version posted. Let me know if you find any issues. I haven't had a lot of time to test and wanted to get something out there. I should have some time to tomorrow if anything comes up.

Thank you for pushing a new version out! I did want to report that I'm able to change abilities out, but what I'm doing before doesn't work - essentially, I was experimenting with stacking 7 or 8 abilities on guys. Now, the Franchise file doesn't even load and crashes the game.

Is this fixable? Like I said, totally willing to donate if need be.

**Comment by ct229** [comment]
Any eta on a new update?

**Comment by bep713** [comment]
Hmm I will take a look at the ability editor soon. I see why the new abilities aren't showing up in the editor so I will fix that in the next update. ETA unknown unfortunately as I work on this when I can. It'll get done soon though.

It's possible that they capped the amount of abilities on one player. I was kinda shocked that they didn't do that from the start haha

**Comment by ct229** [comment]
> Hmm I will take a look at the ability editor soon. I see why the new abilities aren't showing up in the editor so I will fix that in the next update. ETA unknown unfortunately as I work on this when I can. It'll get done soon though.
> 
> It's possible that they capped the amount of abilities on one player. I was kinda shocked that they didn't do that from the start haha

Good to hear and patiently waiting

**Comment by bep713** [comment]
The new abilities are added to v4.0.1, but it looks like you can't add a ton of abilities to one player like you could before. I think they added extra checks to make sure the abilities are valid.

Unfortunately, this means the abilities won't have an effect on the player unless you can add them in-game. I'm not sure if we can even get around this. I'd have to look into it further.

**Comment by bep713** [comment]
I haven't had time to look at the ability editor and decided not to support it for future Madden versions. Closing this issue.
